export const siteKeywords = [
  // Core Professional Identity
  "Data Scientist",
  "AI Specialist",
  "Data Analyst",
  "Data Engineer",
  "Machine Learning Engineer",
  "Business Intelligence",
  "Advanced Analytics",
  "Data Manipulation",
  "Statistical Analysis",
  "Data Modeling",
  
  // Technical Skills - Data Analysis & Visualization
  "Microsoft Power BI",
  "Tableau",
  "Seaborn",
  "Excel Advanced Functions",
  "Pivot Tables",
  "SQL",
  "SAS Programming",
  "Python Pandas",
  "NumPy",
  "Matplotlib",
  
  // Technical Skills - Data Engineering & Big Data
  "Snowflake",
  "Hadoop",
  "Apache Spark",
  "Hive",
  "Cloudera",
  "Databricks",
  "Kafka",
  "Data Lakes",
  "ETL Pipeline Design",
  "Data Processing",
  
  // Technical Skills - Programming & Databases
  "Python",
  "PySpark",
  "MySQL",
  "PostgreSQL",
  "MS SQL",
  "Java",
  "Statistical Analysis",
  "Data Modeling",
  "Data Cleaning",
  "Data Preparation",
  
  // Technical Skills - Cloud & Tools
  "AWS",
  "Amazon Web Services",
  "AWS Glue",
  "AWS Lambda",
  "AWS Redshift",
  "AWS S3",
  "AWS CloudWatch",
  "Azure Machine Learning",
  "Databricks",
  "Apache Airflow",
  "Jenkins",
  "Docker",
  "Git",
  "GitLab",
  "Jira",
  "Google Maps API",
  
  // Technical Skills - Methodologies & Concepts
  "Data Governance",
  "Agile",
  "Scrum",
  "Statistical Methodologies",
  "Data Validation",
  "KPI Tracking",
  "Benchmarking",
  "NLP",
  "Natural Language Processing",
  "Machine Learning",
  "Predictive Modeling",
  "Sentiment Analysis",
  "User Feedback Analysis",
  "Behavioral Data",
  "User Activation",
  "User Retention",
  "Reward Strategies",
  "Pricing Insights",
  "Travel Agencies",
  "Conversational AI",
  "Chatbot",
  "Large Language Models",
  "GPT",
  "Falcon",
  "MPT",
  "Real-time Analysis",
  "Network Monitoring",
  "Meteorological Data",
  "METAR",
  "TAF",
  "Weather Data Standards",
  "SNMP",
  "Real-time Monitoring",
  "Cost Savings",
  "Operational Forecasting",
  "Query Performance",
  "Database Architecture",
  "Geolocation Features",
  "Project Management",
  "Mentoring",
  "Team Leadership",
  
  // Certifications
  "IBM Data Analytics",
  "SAS Programming",
  "Agile with Atlassian Jira",
  "Kaggle for Data Science",
  "Unit Testing",
  "Python Data Structure",
  "CISCO CCNA",
  
  // Education
  "Master of Computer Science",
  "Software Engineering",
  "Information Processing",
  "Bachelor of Computer Science",
  "Information Systems",
  
  // Languages
  "English Advanced",
  "Arabic Native",
  "French Native",
  
  // Companies & Experience
  "Outlier AI",
  "El Djazair Information Technology",
  "National Meteorological Office",
  "Data Science",
  "AI/ML",
  "Travel Technology",
  "Meteorological Services",
  "Information Technology",
  
  // Tools & Technologies
  "Amplitude",
  "Segment",
  "Power BI",
  "PostgreSQL",
  "Google Maps",
  "Agile/Scrum",
  "Data Pipelines",
  "Real-time Applications",
  "Network Devices",
  "Performance Tracking",
  "Comprehensive Reports",
  "Strategic Decisions",
  "Human Resources",
  "Employee Benefits",
  "Dashboard Development",
  "Data Visualization",
  "Business Analysis",
  "Client Collaboration",
  "User Experience",
  "Project Delivery",
  "Technical Capabilities",
  "Data Quality",
  "Compliance",
  "Junior Developers",
  "Team Strengthening",
]